apiVersion: v1
kind: Service
metadata:
  name: messages-rabbit
spec:
  selector:
    name: messages-rabbit
  ports:
  - port: 5672
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: messages-rabbit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: messages-rabbit
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
