apiVersion: v1
kind: Service
metadata:
  name: messages-websocket
spec:
  selector:
    name: messages-websocket
  ports:
  - port: 80
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: messages-websocket
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: messages-websocket
    spec:
      containers:
      - image: messages-websocket:0.3.0
        name: messages-websocket
